baseURL = "https://blog.wmsci.com"
title = "Acto"
author = "wamo"
languageCode = "ja"
DefaultContentLanguage = "ja"
enableInlineShortcodes = true
theme = "Blonde"
enableRobotsTXT = true

# Please enable this feature if the site is available in Japanese, Chinese or Korean.
hasCJKLanguage = true

# If you're using Google Analytics, you can enable this feature.
googleAnalytics = "UA-111958560-24"

# Disqus Comment System
disqusShortname = "acto"

[params]
paginator_pages = "5"

[menu]

  [[menu.main]]
    identifier = "home"
    name = "ホーム"
    url = "/"
    weight = 1

  [[menu.main]]
    identifier = "profile"
    name = "プロフィール"
    url = "/profile/"
    weight = 2

  [[menu.main]]
    identifier = "contact"
    name = "お問い合わせ"
    url = "/contact/"
    weight = 3

  [[menu.foot]]
    identifier = "privacy"
    name = "プライバシーポリシー"
    url = "/privacy/"
    weight = 1

[taxonomies]
category = "categories"
tag = "tags"
archive = "archives"

[privacy]

  [privacy.vimeo]
    disabled = false
    simple = true

  [privacy.twitter]
    disabled = false
    enableDNT = true
    simple = true

  [privacy.instagram]
    disabled = false
    simple = true

  [privacy.youtube]
    disabled = false
    privacyEnhanced = true

[services]

  [services.instagram]
    disableInlineCSS = true

  [services.twitter]
    disableInlineCSS = true
